server:
  port: 11007
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
#  上传文件限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
  application:
    name: stgy-admin
  datasource:
    password: asdsc88Q12
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.32.166:3306/lease?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    #热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  freemarker:
    cache: false
  #    开启aop
#  aop:
#    auto: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.scccy.downloadDy.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    lazy-loading-enabled: true
    auto-mapping-behavior: FULL
  global-config:
    db-config:
      # id使用雪花算法生成： id字段的类型需要使用long类型
      id-type: assign_id

minioSettings:
  url: http://192.168.32.166
  port: 11010
  userName: minioadmin
  password: minioadmin
  bucketName: stgy
scccy:
  redis:
    host: 192.168.32.166
    port: 11020
    password: asdsc88Q12
  jwt:
    alg: "HS256"
    typ: "JWT"
    expire: 604_800_000
    subject: "systemuser-token"
    key: "abcd12345dfverwuio9873rdqr32rdsaawetr43qrcsadt43qrdfds"