server:
  port: 11007
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  application:
    name: stgy-admin
  datasource:
    password: asdsc88Q12
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.32.166:3306/lease?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    #热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  freemarker:
    cache: false
  #    开启aop
#  aop:
#    auto: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.scccy.downloadDy.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    lazy-loading-enabled: true
    auto-mapping-behavior: FULL
  global-config:
    db-config:
      # id使用雪花算法生成： id字段的类型需要使用long类型
      id-type: assign_id



